export const ActionTypes = {
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  SET_PROJECTS: 'SET_PROJECTS',
  FETCH_CLIENTS: 'FETCH_CLIENTS',
  SET_CLIENTS: 'SET_CLIENTS',
  FETCH_INVOICES: 'FETCH_INVOICES',
  SET_INVOICES: 'SET_INVOICES'
}